### ISSUE TITLE
[Neighborhood finder] Looking up a specific address errors out

### ISSUE THREAD

**Issue by piratefsh** [crownheightsaid/mutual-aid-app#172]
## Bug
Looking up `1768 Union Street` on the Neighborhood finder displays an error. The endpoint it hits ` /api/geo/address-metadata`, returns a 500 with an error log of `Address couldn't be found`. 

This address is valid in Brooklyn, so we should look into why this address cannot be found.

Server logs on prod (should be similar to dev):
```
2020-11-05T01:03:10.432892+00:00 app[web.1]: TypeError: Cannot read property 'geometry' of undefined
2020-11-05T01:03:10.432901+00:00 app[web.1]: at exports.addressHandler (/app/src/api/neighborhood-finder/get-address-meta.js:35:9)
2020-11-05T01:03:10.432901+00:00 app[web.1]: at runMicrotasks (<anonymous>)
2020-11-05T01:03:10.432902+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-11-05T01:03:10.433491+00:00 app[web.1]: POST /api/geo/address-metadata 500 148 - 239.425 ms
2020-11-05T01:03:10.433597+00:00 app[web.1]: Address couldn't be found
```

## Expected behavior
- Endpoint should return a 400 instead of 500 with an error message describing that the address cannot be found.
- UI should display the informative error message

**Comment by jconard3** [comment]
Hi @piratefsh, I took a look at this issue and was not able to replicate the behavior for `1768 Union Street` in neither prod or on my local dev instance. I don't yet have permissions to view prod logs but the post to `/api/geo/address-metadata` returns a `200` in my dev. When you are able, could you please attempt looking up `1768 Union Street` on the Neighborhood finder again to see if the issue persists? Thanks.

**Comment by piratefsh** [comment]
Hi @jconard3, thanks for looking at this! It appears that the issue no longer persists with this address. You can still replicate this when an invalid address is entered, e.g. `sjnjkgjkgs` (keyboard smash a random string).

Right now we return a 500, which just displays an unhelpful message `Error loading. Please try again. If it fails again, let us know in #wg_tech`. We should be returning a 4xx error to indicate that the address is not found (and not a server error) and display a more helpful message. 

We can definitely still use help with issue.

**Comment by piratefsh** [comment]
<img width="657" alt="Screen Shot 2021-01-06 at 10 31 26 PM" src="https://user-images.githubusercontent.com/1868400/103848570-acc3bb80-5070-11eb-90bc-5455bc1f0576.png">

Here's a screenshot of an example address that could not be found. This is on prod but should be the same on dev. Do let me know if you have issues replicating this as well.
